version: '3'
services:
  openldap:
    container_name: openldap
    image: 'bitnami/openldap:latest'
    # network_mode: "host"
    networks:
     - my-network
    ports:
      - '1389:1389'
      - '1636:1636'
    environment:
      - LDAP_ADMIN_USERNAME=admin
      - LDAP_ADMIN_PASSWORD=adminpassword
      - LDAP_USERS=customuser
      - LDAP_PASSWORDS=custompassword
      - LDAP_USERS=user01,user02
      - LDAP_PASSWORDS=password1,password2
      - 'LDAP_ROOT=dc=example,dc=org'
      - 'LDAP_ADMIN_DN=cn=admin,dc=example,dc=org'

networks:
    my-network:
      driver: bridge
